### ISSUE TITLE
Render README as HTML

### ISSUE THREAD

**Issue by networkException** [SerenityOS/yaksplained#24]
It would be neat to have the README.md file rendered as HTML for serenityos.github.io/yaksplained / yaksplained.org.

So far I couldn't find a widely used action with that purpose, if somebody knows a good tool for the purpose I'd be happy to implement it with that

**Comment by kleinesfilmroellchen** [comment]
Pandoc should be capable enough. Have a look on how we generate manpages in the main repo.
